package scanner

// ExtendedFingerprintRules contains additional CMS/framework/CDN signatures
// Based on Wappalyzer patterns
// Field order: Name, Pattern, Header, Body (matches cmsSignatures in webfinger.go)
var ExtendedFingerprintRules = []struct {
	Name    string
	Pattern string
	Header  string
	Body    string
}{
	// CMS
	{"WordPress", "", "", "wp-content"},
	{"WordPress", "", "", "wp-includes"},
	{"WordPress", "", "x-powered-by", "wp-"},
	{"Joomla", "", "", "joomla"},
	{"Joomla", "", "", "/media/jui/"},
	{"Drupal", "", "x-generator", "drupal"},
	{"Drupal", "", "", "sites/default/files"},
	{"Magento", "", "", "skin/frontend"},
	{"Magento", "", "", "Mage.Cookies"},
	{"Shopify", "", "", "cdn.shopify.com"},
	{"Shopify", "", "", "Shopify.theme"},
	{"Wix", "", "", "wix.com"},
	{"Squarespace", "", "", "squarespace.com"},
	{"Ghost", "", "", "ghost.io"},
	{"Hexo", "", "", "hexo.io"},
	{"Hugo", "", "", "hugo"},
	{"Typecho", "", "", "typecho"},
	{"DedeCMS", "", "", "dedecms"},
	{"Discuz", "", "", "discuz"},
	{"phpBB", "", "", "phpbb"},
	{"vBulletin", "", "", "vbulletin"},
	{"MediaWiki", "", "", "mediawiki"},
	{"PrestaShop", "", "", "prestashop"},
	{"OpenCart", "", "", "opencart"},
	{"Laravel", "", "set-cookie", "laravel"},
	{"Laravel", "", "", "csrf-token"},
	{"Symfony", "", "x-powered-by", "symfony"},
	{"CodeIgniter", "", "", "codeigniter"},
	{"CakePHP", "", "", "cakephp"},
	{"Yii", "", "", "yii"},
	{"ThinkPHP", "", "x-powered-by", "thinkphp"},
	{"Spring", "", "", "Whitelabel Error Page"},
	{"Spring", "", "", "spring"},
	{"Django", "", "", "csrfmiddlewaretoken"},
	{"Django", "", "", "django"},
	{"Flask", "", "", "werkzeug"},
	{"Express", "", "x-powered-by", "express"},
	{"NestJS", "", "", "nestjs"},
	{"Ruby on Rails", "", "", "csrf-token"},
	{"Ruby on Rails", "", "x-powered-by", "phusion"},
	{"ASP.NET", "", "x-powered-by", "asp.net"},
	{"ASP.NET", "", "x-aspnet-version", ""},
	{"Next.js", "", "x-powered-by", "next.js"},
	{"Next.js", "", "", "__NEXT_DATA__"},
	{"Nuxt.js", "", "", "__NUXT__"},
	{"Vue.js", "", "", "vue.js"},
	{"Vue.js", "", "", "Vue.component"},
	{"React", "", "", "_reactRootContainer"},
	{"React", "", "", "react.production.min.js"},
	{"Angular", "", "", "ng-version"},
	{"Angular", "", "", "angular.min.js"},
	{"jQuery", "", "", "jquery.min.js"},
	{"jQuery", "", "", "jquery-"},
	{"Bootstrap", "", "", "bootstrap.min.css"},
	{"Bootstrap", "", "", "bootstrap.min.js"},
	{"Tailwind CSS", "", "", "tailwindcss"},
	{"Font Awesome", "", "", "font-awesome"},
	{"Google Analytics", "", "", "google-analytics.com"},
	{"Google Tag Manager", "", "", "googletagmanager.com"},
	{"Matomo", "", "", "matomo.js"},
	{"Hotjar", "", "", "hotjar.com"},

	// Servers
	{"Nginx", "nginx", "server", ""},
	{"Apache", "apache", "server", ""},
	{"IIS", "microsoft-iis", "server", ""},
	{"Tomcat", "tomcat", "server", ""},
	{"Jetty", "jetty", "server", ""},
	{"Caddy", "caddy", "server", ""},
	{"LiteSpeed", "litespeed", "server", ""},
	{"OpenResty", "openresty", "server", ""},
	{"Gunicorn", "gunicorn", "server", ""},
	{"uvicorn", "uvicorn", "server", ""},
	{"WebLogic", "weblogic", "server", ""},
	{"WebSphere", "websphere", "server", ""},
	{"JBoss", "jboss", "server", ""},

	// CDN
	{"Cloudflare", "cloudflare", "server", ""},
	{"Cloudflare", "", "", "cf-ray"},
	{"AWS CloudFront", "cloudfront", "server", ""},
	{"AWS CloudFront", "", "x-amz-cf-id", ""},
	{"Akamai", "akamaighost", "server", ""},
	{"Akamai", "", "x-akamai-transformed", ""},
	{"Fastly", "varnish", "via", ""},
	{"Fastly", "cache-", "x-served-by", ""},
	{"KeyCDN", "keycdn", "server", ""},
	{"MaxCDN", "netdna", "server", ""},
	{"Azure CDN", "azurecdn", "server", ""},
	{"Google CDN", "gws", "server", ""},
	{"BunnyCDN", "bunnycdn", "server", ""},

	// Security
	{"WAF", "", "x-waf-", ""},
	{"ModSecurity", "mod_security", "server", ""},
	{"ModSecurity", "modsecurity", "server", ""},
	{"Sucuri", "sucuri", "server", ""},
	{"Wordfence", "", "", "wordfence"},

	// Programming Languages
	{"PHP", "php", "x-powered-by", ""},
	{"PHP", "", "", ".php"},
	{"ASP.NET", "asp.net", "x-powered-by", ""},
	{"ASP.NET", "", "", ".aspx"},
	{"Java", "", "", ".jsp"},
	{"Java", "", "", "servlet"},
	{"Python", "", "", "django"},
	{"Python", "", "", "flask"},
	{"Ruby", "", "", "rails"},
	{"Go", "go-http", "server", ""},
	{"Rust", "actix-web", "server", ""},
	{"Node.js", "express", "x-powered-by", ""},

	// Frameworks
	{"Electron", "", "", "electron"},
	{"Tauri", "", "", "tauri"},
	{"Flutter", "", "", "flutter"},
	{"React Native", "", "", "react-native"},
}
