package scanner

// DefaultSubdomainWordlist contains common subdomain prefixes for brute force
var DefaultSubdomainWordlist = []string{
	"www", "mail", "ftp", "smtp", "pop", "imap", "webmail", "ns1", "ns2",
	"ns3", "ns4", "dns", "dns1", "dns2", "mx", "mx1", "mx2", "mx3",
	"test", "dev", "staging", "prod", "production", "beta", "alpha", "demo",
	"admin", "panel", "cpanel", "whm", "portal", "dashboard", "manage",
	"api", "api2", "api3", "rest", "graphql", "gateway", "edge",
	"app", "app2", "mobile", "m", "wap", "touch",
	"blog", "news", "forum", "community", "bbs",
	"shop", "store", "ecommerce", "pay", "payment", "checkout",
	"cdn", "static", "assets", "media", "img", "images", "image",
	"video", "stream", "live", "tv", "vod",
	"docs", "doc", "wiki", "help", "support", "kb", "faq",
	"git", "gitlab", "github", "svn", "repo", "code", "ci", "cd",
	"jenkins", "ci", "build", "deploy", "release",
	"jira", "confluence", "redmine", "bug", "issue", "tracker",
	"vpn", "proxy", "gateway", "tunnel", "socks",
	"oa", "crm", "erp", "hr", "finance", "bi", "report",
	"monitor", "grafana", "prometheus", "zabbix", "nagios", "cacti",
	"elk", "kibana", "log", "logs", "graylog",
	"redis", "mysql", "postgres", "mongo", "db", "database",
	"cache", "memcached", "queue", "rabbitmq", "kafka",
	"storage", "s3", "oss", "minio", "nas", "backup",
	"auth", "sso", "login", "oauth", "ldap", "cas",
	"chat", "im", "msg", "message", "notification",
	"search", "es", "elastic", "solr", "sphinx",
	"web", "www2", "www3", "origin", "lb", "load",
	"internal", "intranet", "corp", "office", "backend",
	"old", "new", "legacy", "v2", "v3", "next",
	"node", "node1", "node2", "server", "server1", "server2",
	"cluster", "master", "slave", "primary", "replica",
	"smtp", "mx", "exchange", "outlook", "postfix",
	"openvpn", "wireguard", "pptp", "l2tp", "ipsec",
	"ftp", "sftp", "ftps", "scp", "rsync",
	"tomcat", "nginx", "apache", "iis", "lighttpd",
	"docker", "k8s", "kubernetes", "rancher", "portainer",
	"sonar", "nexus", "harbor", "registry",
	"awx", "ansible", "terraform", "puppet", "chef",
	"nacos", "dubbo", "zookeeper", "etcd", "consul",
	"xxl-job", "job", "task", "scheduler", "cron",
	"minio", "oss", "bos", "cos", "obs",
	"wss", "ws", "socket", "websocket", "mqtt",
	"rpc", "grpc", "thrift", "protobuf",
	"webvpn", "ssl", "cert", "tls", "https",
}
